dont continue if IDs not found

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -63,7 +63,15 @@ runs:
           echo 'ITEM_ID='$(jq -r '.data.organization.projectNext.items.nodes[] | select(.content.id==$CONTENT_ID) | .id' project.json --arg CONTENT_ID "$CONTENT_ID") >> $GITHUB_ENV
           echo 'FIELD_ID='$(jq -r '.data.organization.projectNext.fields.nodes[] | select(.name==$FIELD) | .id' project.json --arg FIELD "$FIELD") >> $GITHUB_ENV
           echo 'OPTION_ID='$(jq -r '.data.organization.projectNext.fields.nodes[] | select(.name==$FIELD) | .settings | fromjson | .options[] | select(.name | contains($VALUE)) | .id' project.json --arg VALUE "$VALUE" --arg FIELD "$FIELD") >> $GITHUB_ENV
-      
+
+    - name: Ensure project, item, field, and option were found
+      shell: bash
+      run: |
+        if [ -z "$PROJECT_ID" ]; then echo "Project not found"; exit 1; fi  
+        if [ -z "$ITEM_ID" ]; then echo "Item not found"; exit 1; fi  
+        if [ -z "$FIELD_ID" ]; then echo "Field not found"; exit 1; fi  
+        if [ -z "$OPTION_ID" ]; then echo "Option not found"; exit 1; fi  
+
     - name: Update field
       env:
         GITHUB_TOKEN: ${{ inputs.github_token }}
